# One directory per dataset is recommended
chestxray14_dir = ""
chexpert_dir = ""
mimic_dir = ""
padchest_dir = ""
metachest_dir = "/home/richardt/Projets/bere/datasets/metachest"

# MTL Classes Setup
mtrn = [
    "effusion",
    "lung_opacity",
    "atelectasis",
    "infiltration",
    "nodule",
    "mass",
    "pleural_thickening",
]
mval = [
    "emphysema",
    "fibrosis",
    "hernia",
]
mtst = [
    "cardiomegaly",
    "edema",
    "pneumothorax",
    "consolidation",
    "pneumonia",
]
